[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "N", "S", "C4", "Q", "A", "ANN", "ASYNC"]
ignore = ["ANN101", "ANN102", "B008", "ANN001", "ANN201", "ANN204"]
per-file-ignores = {"backend/tests/*" = ["S101", "S105", "S106", "S603", "S607"]}

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.11"
explicit_package_bases = true
strict = true
warn_return_any = true
warn_unused_configs = true
plugins = []
namespace_packages = true

[tool.coverage.run]
branch = true
source = ["backend/mcp_server", "backend/agent_integration"]

[tool.coverage.report]
show_missing = true
skip_covered = true

